#!C:\Users\VAMP\Documents\GitHub\kiya\env\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'mako==0.7.0','mako-render'
__requires__ = 'mako==0.7.0'
import pkg_resources
pkg_resources.run_script('mako==0.7.0', 'mako-render')
